import{a as l}from"./assets/vendor-bdb8a163.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const c of document.querySelectorAll('link[rel="modulepreload"]'))i(c);new MutationObserver(c=>{for(const n of c)if(n.type==="childList")for(const o of n.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function r(c){const n={};return c.integrity&&(n.integrity=c.integrity),c.referrerPolicy&&(n.referrerPolicy=c.referrerPolicy),c.crossOrigin==="use-credentials"?n.credentials="include":c.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(c){if(c.ep)return;c.ep=!0;const n=r(c);fetch(c.href,n)}})();function f(t,s){const r=[];return s.forEach(i=>{t.includes(i.difficulty)&&r.push(i)}),r}l.defaults.baseURL="https://dummyjson.com/recipes";async function g(){const{data:t}=await l("",{params:{limit:50}});return t}async function L(t){const{data:s}=await l(`/${t}`);return s}async function y(t){const{data:s}=await l("/search",{params:{q:t}});return s}const b="/Rendes-mentor-practic-05/assets/icons-09f5cae6.svg",e={recipesList:document.querySelector(".recipes"),bodyEl:document.querySelector("body"),switchEl:document.querySelector("#switch-theme"),form:document.querySelector(".form"),backdrop:document.querySelector(".backdrop"),modal:document.querySelector(".modal"),parcing:document.querySelector(".parcing"),recipes:"",filtered:"",applyFilter:document.querySelector(".filter"),theme:document.querySelector(".theme"),pathToIcons:b,header:document.querySelector(".header"),checkboxGroup:document.querySelector(".checkbox-group"),loadMoreBtn:document.querySelector("#loadMore"),currentPage:1};function a(t){const s=t.map(({id:r,image:i,name:c,difficulty:n,cuisine:o})=>`<li class="recipe-item" data-id='${r}'>
    <img
        class="recipe-image"
        src=${i}
        alt=${c}
    />
    <div class="recipe-dscr">
        <p class="recipe-name">Name: ${c}</p>
        <p class="recipe-cuisine">Cuisine: ${o}</p>
        <p class="recipe-difficulty">Difficulty: ${n}</p>
    </div>`).join("");e.recipesList.insertAdjacentHTML("beforeend",s)}function v({name:t,difficulty:s,cuisine:r,caloriesPerServing:i,image:c,ingredients:n,instructions:o,prepTimeMinutes:m,cookTimeMinutes:p}){const h=`<h2 class="food-name"><b>Name:</b> ${t}</h2>
          <div class="common-container">
            <div class="descr-container">
              <p class="food-cuisine"><b>Cuisine:</b> ${r}</p>
              <p class="difficulty"><b>Difficulty:</b> ${s}</p>
              <p class="ingredients"><b>Inredients:</b> ${n}</p>
              <p class="instructions"><b>Instructions:</b> ${o}</p>
              <p class="prep-time"><b>Preparation time:</b> ${m} minutes</p>
              <p class="cook-time"><b>Cook time:</b> ${p} minutes</p>
              <p class="calories"><b>Calories:</b> ${i}</p>
            </div>
            <img class="large-image" src="${c}" alt="Food image" />
          </div>`;e.parcing.insertAdjacentHTML("beforeend",h)}function d(t){const i=t/12;return Math.ceil(i)}async function k(t){t.preventDefault();const s=t.target.elements.query.value.trim();if(!s)return alert("Search request must not be blank");const{recipes:r,total:i}=await y(s);e.recipes=r,r.length?(e.currentPage=1,console.log(e.recipes),e.recipesList.innerHTML="",a(r.slice(e.currentPage*12-12,e.currentPage*12)),d(i)>1?e.loadMoreBtn.classList.remove("hidden"):e.loadMoreBtn.classList.add("hidden")):(e.loadMoreBtn.classList.add("hidden"),e.recipesList.innerHTML='<h2 class="empty-result">No matches found</h2>')}function u(t,s){const r=JSON.stringify(s);localStorage.setItem(t,r)}function M(t){const s=localStorage.getItem(t);try{return JSON.parse(s)}catch{return s}}function P(){e.bodyEl.classList.toggle("dark-theme"),e.modal.classList.toggle("dark-theme"),e.header.classList.toggle("dark-theme"),e.checkboxGroup.classList.toggle("dark-theme"),e.bodyEl.classList.contains("dark-theme")?(u("theme","dark"),e.theme.innerHTML=`
      <svg class="moon" height="30" width="30">
        <use href="${e.pathToIcons}#moon"></use>
      </svg>`):(u("theme","white"),e.theme.innerHTML=`
      <svg class="sun" height="30" width="30">
        <use href="${e.pathToIcons}#sun"></use>
      </svg>`)}async function S(){const{recipes:t,total:s}=await g();e.currentPage=1,e.recipes=t,d(s)>1?e.loadMoreBtn.classList.remove("hidden"):e.loadMoreBtn.classList.add("hidden"),e.recipesList.innerHTML="",a(t.slice(e.currentPage*12-12,e.currentPage*12))}function T(t){e.currentPage=1,e.loadMoreBtn.classList.remove("hidden");const s=t.target.form,r=[];for(const i of s)i.checked&&r.push(i.value);if(!r.length)return e.filtered="",e.recipesList.innerHTML="",a(e.recipes.slice(e.currentPage*12-12,e.currentPage*12));e.filtered=f(r,e.recipes),e.filtered.length?(e.currentPage=1,e.recipesList.innerHTML="",a(e.filtered.slice(e.currentPage*12-12,e.currentPage*12)),d(e.filtered.length)>1?e.loadMoreBtn.classList.remove("hidden"):e.loadMoreBtn.classList.add("hidden")):(e.loadMoreBtn.classList.add("hidden"),e.recipesList.innerHTML='<h2 class="empty-result">No matches found</h2>')}function E(){e.loadMoreBtn.classList.add("hidden"),e.currentPage++,e.filtered.length?a(e.filtered.slice(e.currentPage*12-12,e.currentPage*12)):a(e.recipes.slice(e.currentPage*12-12,e.currentPage*12));const t=e.recipesList.firstChild.getBoundingClientRect().height+50;window.scrollBy({top:t,behavior:"smooth"}),e.currentPage===d(e.filtered.length)||e.currentPage===d(e.recipes.length)?e.loadMoreBtn.classList.add("hidden"):e.loadMoreBtn.classList.remove("hidden")}async function B(t){if(!t.target.closest("li"))return;e.parcing.innerHTML="";const s=t.target.closest("li").dataset.id,r=await L(s);e.backdrop.classList.remove("hidden"),v(r),e.backdrop.addEventListener("click",i=>{(i.target.classList.contains("backdrop")||i.target.classList.contains("close-button"))&&(e.backdrop.classList.add("hidden"),e.backdrop.removeEventListener)}),document.addEventListener("keyup",i=>{i.key==="Escape"&&(e.backdrop.classList.add("hidden"),e.backdrop.removeEventListener)})}function $(){M("theme")==="dark"&&(e.bodyEl.classList.toggle("dark-theme"),e.modal.classList.toggle("dark-theme"),e.header.classList.toggle("dark-theme"),e.checkboxGroup.classList.toggle("dark-theme"),e.theme.innerHTML=`
      <svg class="moon" height="30" width="30">
        <use href="${e.pathToIcons}#moon"></use>
      </svg>`)}document.addEventListener("DOMContentLoaded",$);document.addEventListener("DOMContentLoaded",S);document.addEventListener("click",B);e.form.addEventListener("submit",k);e.switchEl.addEventListener("click",P);e.applyFilter.addEventListener("change",T);e.loadMoreBtn.addEventListener("click",E);
//# sourceMappingURL=commonHelpers.js.map
